### ISSUE TITLE
Recipe Error

### ISSUE THREAD

**Issue by NealSavage** [satyrnidae/early-game-buckets#4]
**Issue Description**
Log is showing that some recipe is not loading correctly. 

**Reproduction Steps**
1. Mod installed
2. Join a singleplayer world 
3. See error 

**Expected Behavior**

**Screenshots / Videos**
I guess this is where logs best fits into the question...? Here. https://bytebin.lucko.me/pk0xRCCfSL

**Version Information:**
 - OS: [WINDOWS]
 - Java: [ Java 17] 
 - Minecraft Version: [1.18.2]
 - Fabric Loader Version: [0.13.3]
 - Mod Version: [2.0.0]

**Additional Context**

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/173392746-6c931f10-06fe-4b34-b99d-f46c92d81c5d.png)
I can confirm this issue.

**Comment by satyrnidae** [comment]
This is due to the optional dependency [Kiln](https://www.curseforge.com/minecraft/mc-mods/kiln-fabric) not being installed. Since the dependency is optional, this can generally be ignored as it shouldn't cause any other recipes to fail to load.
